# Generated by Django 3.0.7 on 2020-06-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_1', '0002_firstpage_famous_novelist_firstpage_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='just_check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='firstpage_main_book_of_week',
            name='features',
        ),
        migrations.AlterField(
            model_name='firstpage_famous_novelist',
            name='image_of_novelist',
            field=models.ImageField(upload_to='famous_novelist'),
        ),
        migrations.AlterField(
            model_name='firstpage_famous_novelist',
            name='name_of_author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='firstpage_main_book_of_week',
            name='main_background',
            field=models.ImageField(upload_to='book_of_week'),
        ),
        migrations.AlterField(
            model_name='firstpage_main_book_of_week',
            name='small_image',
            field=models.ImageField(upload_to='book_of_week'),
        ),
        migrations.AlterField(
            model_name='firstpage_mainbackground',
            name='background_image',
            field=models.ImageField(upload_to='background'),
        ),
        migrations.AlterField(
            model_name='firstpage_mainbackground',
            name='small_image_1',
            field=models.ImageField(upload_to='background'),
        ),
        migrations.AlterField(
            model_name='firstpage_mainbackground',
            name='small_image_2',
            field=models.ImageField(upload_to='background'),
        ),
        migrations.AlterField(
            model_name='firstpage_mainbackground',
            name='small_image_3',
            field=models.ImageField(upload_to='background'),
        ),
        migrations.AlterField(
            model_name='firstpage_news',
            name='news_image',
            field=models.ImageField(upload_to='news'),
        ),
        migrations.AlterField(
            model_name='firstpage_reccomended_books',
            name='image_book_1',
            field=models.ImageField(upload_to='reccmended_books'),
        ),
        migrations.AlterField(
            model_name='firstpage_reccomended_books',
            name='image_book_2',
            field=models.ImageField(upload_to='reccmended_books'),
        ),
        migrations.AlterField(
            model_name='firstpage_reccomended_books',
            name='image_book_3',
            field=models.ImageField(upload_to='reccmended_books'),
        ),
        migrations.AlterField(
            model_name='firstpage_reccomended_books',
            name='image_book_4',
            field=models.ImageField(upload_to='reccmended_books'),
        ),
        migrations.AlterField(
            model_name='firstpage_reccomended_books',
            name='image_book_5',
            field=models.ImageField(upload_to='reccmended_books'),
        ),
        migrations.AlterField(
            model_name='firstpage_reccomended_books',
            name='image_book_6',
            field=models.ImageField(upload_to='reccmended_books'),
        ),
        migrations.AlterField(
            model_name='firstpage_reccomended_books',
            name='name_book_1',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='firstpage_reccomended_books',
            name='name_book_2',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='firstpage_reccomended_books',
            name='name_book_3',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='firstpage_reccomended_books',
            name='name_book_4',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='firstpage_reccomended_books',
            name='name_book_5',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='firstpage_reccomended_books',
            name='name_book_6',
            field=models.CharField(max_length=150),
        ),
    ]
