# Generated by Django 3.0.7 on 2020-06-17 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template_1', '0003_auto_20200616_2219'),
    ]

    operations = [
        migrations.DeleteModel(
            name='just_check',
        ),
    ]
