# Generated by Django 3.0.7 on 2020-06-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_1', '0005_auto_20200617_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book_image', models.ImageField(upload_to='reccmended_books')),
                ('book_name', models.CharField(max_length=150)),
                ('book_category', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='firstpage_reccomended_books',
        ),
    ]
