# Generated by Django 3.0.7 on 2020-06-18 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template_1', '0006_auto_20200618_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='book_category',
        ),
    ]
