# Generated by Django 3.0.7 on 2020-06-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_1', '0011_books_author_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author_image',
            field=models.ImageField(default='no image available', upload_to='author_image'),
        ),
    ]
