# Generated by Django 3.0.7 on 2020-06-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_1', '0012_auto_20200627_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='EMAIL',
            field=models.EmailField(default='none', max_length=254),
        ),
        migrations.AlterField(
            model_name='books',
            name='author_image',
            field=models.ImageField(default='no_image_available.jpg', upload_to='author_image'),
        ),
        migrations.AlterField(
            model_name='books',
            name='review',
            field=models.TextField(default='oops! no reviews '),
        ),
    ]
