# Generated by Django 3.0.7 on 2020-06-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_1', '0013_auto_20200627_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author_image',
            field=models.ImageField(default='author_image/no_image_available.jpg', upload_to='author_image'),
        ),
    ]
