# Generated by Django 3.0.7 on 2020-06-27 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('template_1', '0014_auto_20200627_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='EMAIL',
        ),
        migrations.RemoveField(
            model_name='books',
            name='review',
        ),
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMAIL', models.EmailField(default='none', max_length=254)),
                ('profession', models.CharField(default='unemployed', max_length=150)),
                ('profile_pic', models.ImageField(default='no_image_available.jpg', upload_to='reviewist')),
                ('review', models.TextField(default='oops! no reviews ')),
                ('book_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template_1.books')),
            ],
        ),
    ]
