# Generated by Django 3.0.7 on 2020-06-27 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template_1', '0015_auto_20200627_1427'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reviews',
            new_name='review',
        ),
    ]
